name: Git Pull 13.0_staging and Odoo Restart

on:
    push:
        branches:
            - 13.0_staging

jobs:
    deploy-13-staging:
        runs-on: ubuntu-latest
        steps:
            - name: SSH Comamnds
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_PATH: ${{ secrets.PROJECT_PATH_STAGING }}
              with:
                  host: "${{ secrets.SSH_HOST }}"
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY}}
                  envs: PROJECT_PATH
                  script: |
                      cd $PROJECT_PATH
                      git pull --rebase
                      git submodule update
                      docker restart odoo-halpern-staging
                      docker restart odoo-masteragua-staging
